### PR TITLE
Fix manuscripts on dashboard

### LINKED ISSUE #1014: Dashboard shows submissions of other users
**Steps to Reproduce:**

- Go to https://staging--xpub.elifesciences.org/
- Login with the an Orcid sandbox user
- All submissions for all users, including unfinished submissions, are displayed

image 4

- Users are unable to continue submissions initially created by other users.

screen shot 2018-11-09 at 15 52 55

### PR DESCRIPTION
**Pull request by damnhipster**
Closes #1014 

I'm unable to test this outside of Staging as our login mock only supports a single user.

### CODE REVIEW

**Comment by damnhipster** [comment]
There currently isn't any functionality where we need a `Manuscript.all` function, or a `File.all` or `User.all`. It's safer to not expose the methods at all until they're needed.

**Comment by diversemix** [comment]
OK, so let's hide `all` by overriding to throw an exception - and do the rename on the existing function as currently its name is misleading.

**Comment by damnhipster** [comment]
I think this requires a different refactor where we query the user for their manuscripts, rather than querying manuscripts by user. I thought it may be worth doing it in a separate pull request.

The existing functions within the `Manuscript` model expect a user to be passed in, such as `.find` and `.findByStatus`. I suggest we keep it consistent until we've managed to perform the above refactor.

**Comment by diversemix** [comment]
Ok ... I'm with you on the application logic of `user -> manuscript` and lets get this in so that its fixed short-term on the understanding that it needs to be changed. :+1:

**Pull request merged**
