### PR TITLE
add track to google analytics pages

### LINKED ISSUE #1358: Track page views with Google Analytics
Xpub is a single page app. This means that Google Analytics does not track page view by default.

We should change the router on the React app so that it tracks page view automatically.

You can find more information [here](https://github.com/elifesciences/elife-xpub/issues/1077#issuecomment-454012354)

- [x] change react-router to track page views on Google Analytics 
- [x] track the page views whenever the location within the address bar changes
- [x] use a `pageview` event with `('/some-page')`

### PR DESCRIPTION
**Pull request by jyenes**
#### Background
pages need to be tracked by Google Analytics
What does this PR do?
tracks visited pages

closes #1358

### CODE REVIEW

**Comment by hdrury1** [comment]
@jyenes presume this actually closes #1358? ;)

**Review by hem-brahmbhatt — APPROVED** [review]
Code looks good, will do some testing

**Review by diversemix — APPROVED** [review]

**Comment by hem-brahmbhatt** [comment]
@jyenes I seem to be getting duplicate pageview events in the console.

screen shot 2019-01-23 at 14 35 24

**Comment by jyenes** [comment]
with the last commit, we shouldn't have the duplicate issue @damnhipster

**Comment by diversemix** [comment]
Assume we are waiting on @damnhipster to check? ... do we have any tests in for this @jyenes ?

**Review by hem-brahmbhatt — APPROVED** [review]

**Pull request merged**
