### PR TITLE
WIP extend maximum suggested editors to 6 instead of 2

### PR DESCRIPTION
**Pull request by jsms90**
#### What does this PR do?
- allow authors to suggest up to 6 senior editors & 6 reviewing editors, instead of max 2

Note: validation message shows the new max no. automatically

#### Any relevant tickets
#557 

#### How has this been tested?
- add min, max limits to server-side validation
- choose 6 senior editors & 6 reviewing editors in e2e test

### CODE REVIEW

**Comment by jsms90** [comment]
@hdrury1 ok so this is currently working i.e. product requirements satisfied :+1: 

But design wise it doesn't look great.

---
With 4 people chosen:
image

---

But then 5 people:
image

---

And then with 6, when we get the message back:

image

---

Basically this isn't a new issue - it always existed on mobile, but it's more obvious now that we're allowing more than 2 reviewers.

I notice that this is actually covered by another ticket - #448. How about we merge this as it is and then, assuming you also feel that this is a significant design issue, I can pick up #448 next?

**Comment by jsms90** [comment]
Getting an error in the tests within CI but seemed to be fine locally before I pushed up.

Seems to be an issue with using eLife's `/people` endpoint
image

Investigating now

**Comment by tamlyn** [comment]
Did you forget to check in the new Replay recordings (since you are fetching new editors)?

**Comment by jsms90** [comment]
@tamlyn Yep, exactly it. Trying to do that now. But actually the e2e tests do seems to be having problems locally (different problems) & I just didn't realise.

The whole happy path test fails for me right at the start, when it tries to fetch author details from Orcid :confused: 
image

So I can't even get to the People Picker part.

**Comment by jsms90** [comment]
Oh no, that only happens when I add `REPLAY=record`

When I run the e2e test with `REPLAY=replay`, the whole thing passes fine. People Picker and all.

**Comment by hdrury1** [comment]
@jsms90 Just in response to your comment, yep I'm happy for this to be merged as is once the tests pass.

**Pull request merged**
