### PR TITLE
exposing the configuration for google analytics on client side

### PR DESCRIPTION
**Pull request by jyenes**
#### Background
expose the configuration of the GA id on the client side

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

open source and see if the GA tag is present

### CODE REVIEW

**Review by Cooryd — APPROVED** [review]
Have just wrestled with the `isPublic` setting myself. May be worth us commenting in the `default.js` that `isPublic` is required to make the config public so no one else misses this?

Looks good though

**Comment by hem-brahmbhatt** [comment]
> Have just wrestled with the `isPublic` setting myself. May be worth us commenting in the `default.js` that `isPublic` is required to make the config public so no one else misses this?
> 
> Looks good though

There is an issue to make this easier: https://github.com/elifesciences/elife-xpub/issues/1353

**Review by diversemix — APPROVED** [review]

**Comment by diversemix** [comment]
@jyenes ... you may want to check my conflict resolution (I merged in @Cooryd 's hotjar change first)

**Review by SemraSh — APPROVED** [review]

**Comment by SemraSh** [comment]
This PR is only initialising google analytics in the app. The event trackings are going to be created in an upcoming ticket as soon as they are confirmed by @hdrury1 .

The user can be tracked in the Real-Time / Overview tab in the analytics.google dashboard as seen below
image

**Pull request merged**
