### PR TITLE
Enable SFTP in end2end

### PR DESCRIPTION
**Pull request by giorgiosironi**
Once https://github.com/elifesciences/builder-configuration/pull/26 and similar are in, this seems to be the only change.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
We are ready to enable now (once the pipeline is green):
```
elife@prod--alfred:~$ sftp -P 2222 ejpdummy@end2end--xpub--1.elife.internal          
The authenticity of host '[end2end--xpub--1.elife.internal]:2222 ([10.0.2.252]:2222)' can't be established.
ED25519 key fingerprint is SHA256:4uZ+yn6N7EIkr3kPm2Zy8FoEd/8bbuoDPXayaiG8MDA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[end2end--xpub--1.elife.internal]:2222,[10.0.2.252]:2222' (ED25519) to the list of known hosts.
ejpdummy@end2end--xpub--1.elife.internal's password: 
Connected to end2end--xpub--1.elife.internal.
```

**Review by diversemix — APPROVED** [review]

**Comment by diversemix** [comment]
@giorgiosironi ... I'll let you merge :+1:

**Comment by giorgiosironi** [comment]
Will wait on this to integrate the end2end test first, since it may break it.

**Review by hem-brahmbhatt — APPROVED** [review]

**Comment by giorgiosironi** [comment]
Let's go with it, to be able to work on expanding end2end tests.

**Pull request merged**
