### PR TITLE
Static pages mobile nav

### LINKED ISSUE #820: Create dropdown component for mobile version of static pages
**Product requirements/Acceptance criteria:**

Depends on #821 

Functional:
- The words in the top button of the dropdown should show the words associated with the current page
- The list below should contain all of the sub-pages that a user can navigate to within the Author Guide/Reviewer Guide/Contact Us page that they are on
- When a user clicks on .... (which part of this component? just the words? just the down chevron? both? the whole bar?)
  - the dropdown should appear
  - the down chevron should turn into an up chevron
- When a user clicks on one of the items in the dropdown menu
  - the user should be navigated to the chosen sub-page  

**Relevant links to design(s):**
image
image

### PR DESCRIPTION
**Pull request by jsms90**
#### What does this PR do?
- Adds the NavigationDropdown to StaticPages
- Removes internal state from NavigationDropdown (again :yum:) & pass info directly from StaticPages into react-select component

#### Any relevant tickets
fixes #820 

#### How has this been tested?
Change `makeWrapper`, to update existing tests. It now:
- wraps everything in `ThemeProvider`
- passes down history from `MemoryRouter` into `Route` component, which then renders `StaticPage`

### CODE REVIEW

**Comment by jsms90** [comment]
Ahh! How frustrating!
When I was building this component, I was obviously using styleguidist. But styleguidist doesn't have the right fonts applied :rage:

**Comment by hdrury1** [comment]
Lgtm!

**Comment by diversemix** [comment]
See #913

**Comment by damnhipster** [comment]
Awesome job!

**Comment by jsms90** [comment]
@damnhipster Thanks buddy :grin:

**Pull request merged**
