### PR TITLE
Adding the focuses to subjectAreas

### LINKED ISSUE #627: Combine 'expertises' and 'focuses' from the eLife API
Currently keywords in the Person Pods are comprised only of the 'expertises' field from the API.

- The Person Pod should show a person's research focuses as well as their expertises
- A user should be able to search for a person by their focuses
- All of the information, comma separated, should appear on the third line of the Pod
- The order of information does not matter
- Text should be colourTextSecondary

### PR DESCRIPTION
**Pull request by SemraSh**
#### What does this PR do?
Combines `expertises` and `focuses` as subjectAreas for senior and reviewing editors

#### Any relevant tickets
fixes #627

#### How has this been tested?
Jest

### CODE REVIEW

**Comment by diversemix** [comment]
Did you run the unit tests and browser tests locally? ( you could just update the "How has this been tested?
" section) :+1:

**Comment by jsms90** [comment]
@diversemix this is a WIP

**Comment by diversemix** [comment]
Ok, guess you are just going through raising PRs :+1:

**Comment by hdrury1** [comment]
Expertises and focuses are both required fields in the api for editors.

However, they are NOT required fields for other person types such as staff.

**Pull request merged**
