### PR TITLE
Parallel build of Docker images

### PR DESCRIPTION
**Pull request by giorgiosironi**
#### Background

Real world test case for https://github.com/elifesciences/issues/issues/4911 but nothing to see here yet.

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

- [x] performing builds locally with `--no-cache` and with/without `--parallel`: 10m30s to 6m30s
- [x] performing builds on Jenkins current nodes (`containers--medium`) with `--no-cache` and with/without `--parallel`: 10m15s to 10m57s
- [x] performing builds on `containers--xlarge` with `--no-cache` and with/without `--parallel`: 5m to 3m15s
~- [x] performing builds on `containers--2xlarge` with `--no-cache` and with/without `--parallel`: 5m to 3m-3m10s~
- [x] performing builds on Jenkins updated nodes (`containers--xlarge` with `gp2`), with `--no-cache`, with `--parallel`: 3m to 3m30s

Seems there is a bottleneck on `containers` nodes, that's why I'm trying with a few different instance sizes.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
`iostat` oscillates between CPU usage and IO wait, but it looks like we could benefit from more CPU (probably in general):
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          30.18    0.00   15.45   34.19    0.41   19.77
```
Just taking a look at the cost if we doubled the instances...

**Comment by giorgiosironi** [comment]
Costs per month in dollars up to June 2019, rough estimate since Jenkins doesn't tag very well:
```
19.84 | 18.46 | 17.60 | 20.53 | 23.18 | 70.85
```
I think we can spend more on this for better performance.

**Comment by giorgiosironi** [comment]
Actually even lower, [filtering for tag `Name: containers-jenkins-plugin`](https://console.aws.amazon.com/cost-reports/home?#/custom?groupBy=None&hasBlended=false&hasAmortized=false&excludeDiscounts=true&excludeTaggedResources=false&timeRangeOption=Last6Months&granularity=Monthly&reportName=&reportType=CostUsage&isTemplate=true&filter=%5B%7B%22dimension%22:%22Service%22,%22values%22:%5B%22Amazon%20Elastic%20Compute%20Cloud%20-%20Compute%22%5D,%22include%22:true,%22children%22:null%7D,%7B%22dimension%22:%22TagKeyValue%22,%22values%22:null,%22include%22:true,%22children%22:%5B%7B%22dimension%22:%22Name%22,%22values%22:%5B%22containers-jenkins-plugin%22%5D,%22include%22:true,%22children%22:null%7D%5D%7D%5D&chartStyle=Group&forecastTimeRangeOption=None&usageAs=usageQuantity&startDate=2019-01-01&endDate=2019-06-30):
```
10.11 | 8.55 | 4.40 | 3.94 | 6.03 | 24.06
```

**Comment by giorgiosironi** [comment]
We are out of andon so unblocking?

**Comment by giorgiosironi** [comment]
Encountered some throttling, redoing tests with T2 unlimited on.

**Comment by giorgiosironi** [comment]
Disappointing 4m45s in https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-2293/4/pipeline/22

**Comment by giorgiosironi** [comment]
Even worse at 6+ minutes in https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-2293/5/pipeline/22 what are we paying CPUs for...

**Comment by giorgiosironi** [comment]
A few tests but I also want to change the disk type from `standard` to `gp2`, that's in the [AMI apparently](https://console.aws.amazon.com/ec2/home?region=us-east-1#Images:visibility=owned-by-me;sort=desc:creationDate).

**Comment by diversemix** [comment]
Reading here ... I wad unaware were even had an IO credit balance

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html

**Comment by giorgiosironi** [comment]
> an IO credit balance

With anything else than `io1` volumes you never know what you are going to get, the the provisioned IOPS are so expensive that nothing at eLife justifies using those. Most old projects are on `magnetic` (previous generation HDD) whereas the new default for everything should be `gp2` (bang-for-the-buck SSD).

**Comment by giorgiosironi** [comment]
How to [track `BurstBalance`](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(metrics~(~(~'AWS*2fEBS~'VolumeWriteOps~'VolumeId~'vol-009725408fba8c7cf~(visible~false))~(~'.~'VolumeReadOps~'.~'.~(visible~false))~(~'.~'BurstBalance~'.~'vol-02f9e22e1a7588ec7))~view~'timeSeries~stacked~false~region~'us-east-1);query=~'*7bAWS*2fEBS*2cVolumeId*7d*20vol-02f9e22e1a7588ec7) for a `gp2` volume, here the one of `elife-alfred--prod`.

**Comment by giorgiosironi** [comment]
A general picture of `BurstBalance` across all our `gp2` volumes (used by all `elife-xpub--*` stacks for example) during a 24-hour period. Shows nothing goes under 99% of the balance, even when tracking one week we have 97% at a minimum:
Screenshot_2019-07-15 CloudWatch Management Console

**Comment by diversemix** [comment]
Could we try `io1` as an experiment?

**Comment by giorgiosironi** [comment]
With a `gp2` and 300 IOPS, 3m36s on the first launch. Collecting more data and waiting for [metrics to appear](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~();query=~'*7bAWS*2fEBS*2cVolumeId*7d*20vol-07835be23e9a80cba) to understand if and where there is a bottleneck. 

A `io1` could provide a fixed maximum IOPS, but it needs a number to set at that maximum. Also we may not even bursting through the 300 IOPS (proportional to the size, 100 GB). The burst limit is 3000 IOPS ~on top of that~ in total. Also:

<blockquote>
If you notice that your volume performance is frequently limited to the baseline level (due to an empty I/O credit balance), you should consider using a larger gp2 volume (with a higher baseline performance level) or switching to an io1 volume for workloads that require sustained IOPS performance greater than 16,000 IOPS. 
</blockquote>

**Comment by giorgiosironi** [comment]
We seems table between 3m and 3m30s.

**Comment by giorgiosironi** [comment]
Confirmed the `gp2` bursts and takes the balance down to [98%](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(view~'timeSeries~stacked~false~start~'-PT3H~end~'P0D~region~'us-east-1~metrics~(~(~'AWS*2fEBS~'BurstBalance~'VolumeId~'vol-08dab17fbeb8bbce7)));query=~'*7bAWS*2fEBS*2cVolumeId*7d*20vol-08dab17fbeb8bbce7) so it is effectively equivalent to a 3000 IOPS volume. Even the peak throughput didn't get over 1000 IOPS:
Screenshot_2019-07-15 Volumes EC2 Management Console

**Review by diversemix — APPROVED** [review]
Great!

**Review by Cooryd — APPROVED** [review]

**Pull request merged**
