### PR TITLE
2108 - send over lastStepVisited on autosave

### LINKED ISSUE #2108: Investigate lastStepVisited being set on auto save
## Background

We removed the savePage resolver in favour of setting lastStepVisited on the auto save. We need to make sure this is working with the `newSubmit` code thats been added recently.

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background
Includes the last step visited information on autosave. 

Attempts a save immediately if the page location changes.

#### Any relevant tickets

Closes #2108

### CODE REVIEW

**Comment by diversemix** [comment]
The interval is a good point - I think we do need to force save when a new page is visited ... :thinking:

**Comment by Cooryd** [comment]
I'm thinking we need to force save after navigating if no pending save is happening. also may be worth looking into doing the same thing on `willUnmount` __IF__ the submission hasn't just been submitted

**Comment by diversemix** [comment]
Would this trick work... https://stackoverflow.com/a/30725868/628534
Forcing the autosave to happen then resetting it to be periodic again

**Comment by diversemix** [comment]
LGTM :smile:

**Review by diversemix — APPROVED** [review]

**Review by erezmus — APPROVED** [review]

**Pull request merged**
