### PR TITLE
Printing replay logs in Jenkins during browser tests

### PR DESCRIPTION
**Pull request by hem-brahmbhatt**
This is to debug the sciencebeam error we're seeing [here](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1318/2/pipeline/64/)

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Don't see much of a difference in https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1326/1/pipeline :thinking:

**Comment by hem-brahmbhatt** [comment]
I've retriggered the pipeline, I've seen behaviour in the past where changes to the Jenkinsfile doesn't get picked up the first time the pipeline runs.

**Comment by hem-brahmbhatt** [comment]
@giorgiosironi It's looking better now, you can see more verbose logs:

https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1326/3/pipeline/64#step-68-log-92

Do you know how to consistently reproduce the issue on Jenkins?

**Comment by giorgiosironi** [comment]
If you look at build 1:
https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1326/1/pipeline
the command line being used is:
```
+ IMAGE_TAG=b63696ea8c7fe864d599448e10829592c9593be1 NODE_ENV=production NODE_CONFIG_ENV=test DEBUG=replay PGDATABASE=test_browser docker-compose -f docker-compose.yml ...
```
so it seemed it was picking up the Jenkinsfile?
Talking about state between builds, we do `docker-compose down -v` all the time to avoid interactions so build 1 and 3 should effectively be the same, but their output isn't.

**Comment by hem-brahmbhatt** [comment]
@giorgiosironi I changed the code between build 2 and 3, so it's working now.

**Comment by giorgiosironi** [comment]
Ah, the issue about `test:browser` then. Usually I resort to running many pipelines at the same time, they can use different nodes to complete in parallel.

**Comment by giorgiosironi** [comment]
This has failed:
https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1326/8/

**Comment by hem-brahmbhatt** [comment]
The logs show that replay successfully mocked out sciencebeam, even though the test still failed.

https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1326/8/pipeline#step-68-log-108

Replay is also logging outgoing server-side requests which don't have a mock associated, and there doesn't seem to be any of these requests being made.

I believe the problem is either with the test fixture, or our code.

@diversemix @giorgiosironi I suggest we merge this change in for the time being.

**Review by diversemix — APPROVED** [review]

**Pull request merged**
