### PR TITLE
refactor and make the uploads running on parallel

### LINKED ISSUE #1449: Multiple "Supporting File" uploads in parallel

### PR DESCRIPTION
**Pull request by jyenes**
#### Background
we need the uploads running in parallel

What does this PR do?
closes #1449 

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [ ] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

### CODE REVIEW

**Review by hem-brahmbhatt — APPROVED** [review]
Code looks good

**Comment by diversemix** [comment]
Does this work? I had though we did it sequentially for a reason ... that being a race condition on the server. @hdrury @BlueReZZ  @cooryd ?

I will check ASAP

**Comment by diversemix** [comment]
OK ... we have no tests for this :sob: ... But by code inspection is *should* be ok.

**Comment by Cooryd** [comment]
Race conditions were the reason we were doing this sequentially originally, seeing as we are calling `find()` before every operation and save over the manuscript though I would assume this would work in most scenarios now. This should be thoroughly tested (manually) though to make sure there aren't any possible error scenarios ie: some files failing or the page reloading during upload.

**Pull request merged**
