### PR TITLE
Allow S3_ENDPOINT environment variable

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/elifesciences/elife-xpub/issues/1064

Useful to get `app` to talk to the `fakes3` container rather than a real S3 bucket. We would run `fakes3` in CI, too, despite not using it by default for now.

Shouldn't affect tests as they have a `test` environment that is separate from `ci` anyway. `ci` would be used to run pull request review environments.

Probably `ci` is used also for `elife-xpub--ci` usage in the `develop` branch, but right now the environment variable should be empty so it should be irrelevant.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I cannot get this to run locally, which is not a good sign.

**Comment by damnhipster** [comment]
That part of the config expects an `AWS.Endpoint` instance.

https://github.com/elifesciences/elife-xpub/blob/develop/config/test.js#L33-L35

**Comment by giorgiosironi** [comment]
Good example, thanks. I'll also sort out how the app can be started in Jenkins with the `docker-compose.ci.yml` configuration that we use for tests, since at the moment it can't and it breaks the testing of this.

**Comment by diversemix** [comment]
Failing with:
```
FAIL server/xpub-server/entities/manuscript/resolvers/uploadManuscript.test.js (12.803s)
  ● Manuscripts › uploadManuscript › fails if manuscript doesn't belong to user
    CredentialsError: Missing credentials in config
      at Immediate._onImmediate (node_modules/aws-sdk/lib/http/node.js:83:34)
  ● Manuscripts › uploadManuscript › fails if manuscript doesn't belong to user
    TypeError: Cannot read property 'close' of undefined
      46 | 
      47 |     afterEach(done => {
    > 48 |       s3Server.close(done)
         |                ^
      49 |     })
      50 | 
      51 |     it("fails if manuscript doesn't belong to user", async () => {
```

Probably need these creds: https://github.com/elifesciences/elife-xpub/blob/d9264b1f87088407cc52606fe18c6b297c7d16ca/config/test.js#L24

**Comment by diversemix** [comment]
@giorgiosironi ... you might find this command helpful:
```
NODE_ENV=ci node -e "const c = require('config'); console.log(JSON.stringify(c.get('aws'), null, 4));"
```
(running in the root folder where `package.json` lives)

**Comment by diversemix** [comment]
ok ... @giorgiosironi ... looks like the `uploadManuscript.test.js` actually starts its own server and so having a fakes3 one conflicts ...see: https://github.com/elifesciences/elife-xpub/blob/b82a4896b3b7195338b33a2f29ca226c5e580791/server/xpub-server/entities/manuscript/resolvers/uploadManuscript.test.js#L40

**Comment by damnhipster** [comment]
#1123 may help with this

**Comment by diversemix** [comment]
@damnhipster Can you specify how that would help? This turned out not to be about config.

**Comment by damnhipster** [comment]
I'm able to reproduce the issue locally by running `NODE_ENV=ci yarn test server/meca/export.test.js`. Tests are expected to be run using `NODE_ENV=test`. We can hardcode this.

**Comment by damnhipster** [comment]
> @damnhipster Can you specify how that would help? This turned out not to be about config.

It's hard to tell whether we're loading `config/test.js` which is necessary for the tests to pass. I'm not sure if `config/ci.js` is overriding things or if `config/test.js` is loaded at all. My theory is that it's the latter.

> ok ... @giorgiosironi ... looks like the `uploadManuscript.test.js` actually starts its own server and so having a fakes3 one conflicts ...see:

The server that gets started is expected to be on a random port as per `config/test.js`.

**Comment by diversemix** [comment]
@giorgiosironi ... pushed a fix.

**Pull request merged**
