### PR TITLE
revert(dropzone-molecule): remove upload progress from dropzone molecule

### PR DESCRIPTION
**Pull request by dryhten**
re #548

### CODE REVIEW

**Comment by diversemix** [comment]
@dryhten Can you confirm that this is all that is needed to re-instate the old behaviour? ... if it is feel free to merge :)

**Comment by diversemix** [comment]
@dryhten ... I've updated the version of pubsweet client.

**Comment by dryhten** [comment]
I would update the pubsweet client version as part of a different PR. This way it's easier to test things with the websocket on the demo websites (e.g. publish that version and see if the browser is able to connect to the websocket server successfully after login).

Why did you update the pubsweet cli too? I would either update all pubsweet packages to latest version or just the client :)

**Comment by dryhten** [comment]
https://github.com/elifesciences/elife-xpub/pull/558

**Pull request merged**
