### PR TITLE
Update the prediction dynamically

### LINKED ISSUE #1804: Modify the upload progress prediction
Currently the upload progress for the manuscript follows an algorithm (see #839). The accuracy of this algorithm has been analysed as part of #1491

There have been a number of users who have had a very bad experience - due to the prediction of time to upload being underestimated. This is very likely due to network conditions or similar outside of our control.

Therefore it is necessary that the algorithm be adaptive to the network conditions. From the previous analysis, the prediction algorithm is a good reasonable first guess. However, this should be changed as we receive data from the uploaded file.

It is envisaged this will be done to 3 steps:

- [x] Abstract the prediction time
- [ ]  Making upload asynchronous, to allow us the opportunity to update the prediction
- [ ]  Updating the prediction given the speed of upload.

## NOTE: This has been moved to a new ticket to accommodate the first step.

/cc @hdrury1 @chugginselifesciences

### PR DESCRIPTION
**Pull request by diversemix**
#### Background

Fixes the issues where users get stuck for a long time at 99%

#### Any relevant tickets

Closes #1804

#### How has this been tested?

In review env and more tests added.

### CODE REVIEW

**Review by Cooryd — APPROVED** [review]

**Review by will-byrne — APPROVED** [review]

**Review by SemraSh — APPROVED** [review]

**Comment by diversemix** [comment]
Not finished some serious issues with scaling :/

**Comment by diversemix** [comment]
This needs testing in the review environment - so have push some code that will check this.

**Comment by diversemix** [comment]
Happy with things now - please re-review @Cooryd @jyenes @will-byrne @SemraSh

**Review by Cooryd — APPROVED** [review]
Looks good

**Pull request merged**
