### PR TITLE
WIP : First stab at an admin page - not to be merged

### PR DESCRIPTION
**Pull request by diversemix**
#### Background

Creates an Admin page

#### Any relevant tickets

Not really - just playing at the weekend

#### How has this been tested?

Locally - though I do need to write some tests and break out the administrator list into a separate config file... or consider adding a flag to the database.

### CODE REVIEW

**Comment by diversemix** [comment]
@tamlyn / @Cooryd ... this is an idea I had while Gaby was asleep after our Saturday walk!  - so I thought I'd have a go. I'd be interested in your thoughts as to my approach.

**Comment by tamlyn** [comment]
I think an admin page will be useful/essential. But I would be tempted to either keep it separate from the main app code or fully integrate it with user roles and teams. As it stands it feel like a half way solution.

**Comment by diversemix** [comment]
@tamlyn thanks for the input - this is something @Cooryd has suggested too, yeah I guess this is something we could "slip in quickly" if needed - but what you suggest is defo the longer term solution :+1:

**Comment by diversemix** [comment]
@hdrury1 - I'd like to just close this down but raise a task to create some `rudimentry` Admin pages for release. I propose these are done in the style of xPub and are intended for developers and staff to see what is going on xPub-wize.

/cc @Cooryd

**Comment by jsms90** [comment]
I guess the fact that we've got this PR, is really just highlighting how urgent it is for the staff to have their own dashboard on xpub?

From speaking to @hdrury1 and @chugginselifesciences briefly on Wednesday, it sounds like a staff dashboard is likely to be the next body of work, to be done straight after first release (since staff will need their own view of the dashboard, in order to then go in and complete the QC step).

I suppose the question is, how essential is it for staff to have a "rudimentary" dashboard before first release? Or can we afford to wait until just after first release, given that this is going to be the next piece of work anyway?

**Comment by diversemix** [comment]
Well ... this PR also shows how simple it is to knock one up ... but as Tam pointed out we should probably start thinking about Teams and Roles anyhow. This is an area that we should perhaps book a meeting to throw around some ideas. What do you think @hdrury1  ?

**Comment by damnhipster** [comment]
Awaiting requirements from product

**Pull request closed without merging**
