### PR TITLE
Add logs to TestCafé setup and teardown

### PR DESCRIPTION
**Pull request by giorgiosironi**
Also to diagnose https://github.com/elifesciences/elife-xpub/issues/1228

The verbosity is low (these will be logged each once per TestCafé test), and Jenkins itself will label the output with timestamps.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
[Build 2](https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-xpub/job/PR-1230/2/console) waited for a while:
```
09:43:49 test/helpers/setup.js::startServer
09:43:49 test/helpers/setup.js::startServer await start
```
and then timed out:
```
09:44:45    1) - Error in fixture.before hook -
09:44:45       TimeoutError: Knex: Timeout acquiring a connection. The pool is
09:44:45       probably full. Are you missing a .transacting(trx) call?
09:44:45 
09:44:45       Browser: HeadlessChrome 71.0.3578 / Linux 0.0.0
09:44:45 
09:44:45          48 |    // A new query builder instance.
09:44:45          49 |    queryBuilder: function queryBuilder() {
09:44:45          50 |      return client.queryBuilder();
09:44:45          51 |    },
09:44:45          52 |    raw: function raw() {
09:44:45        > 53 |      return client.raw.apply(client, arguments);
09:44:45          54 |    },
09:44:45          55 |    batchInsert: function batchInsert(table, batch) {
09:44:45          56 |      var chunkSize = arguments.length > 2 && arguments[2]
09:44:45       !== undefined ? arguments[2] : 1000;
09:44:45          57 |
09:44:45          58 |      return (0, _batchInsert3.default)(this, table, batch,
09:44:45       chunkSize);
09:44:45 
09:44:45          at Function.raw
09:44:45       (/home/xpub/node_modules/knex/lib/util/make-knex.js:53:25)
09:44:45          at Object.executeSql
09:44:45       (/home/xpub/node_modules/pubsweet-server/src/jobs/index.js:19:17)
09:44:45          at Contractor.isInstalled
09:44:45       (/home/xpub/node_modules/pg-boss/lib/contractor.js:55:22)
09:44:45          at Contractor.start
09:44:45       (/home/xpub/node_modules/pg-boss/lib/contractor.js:91:19)
09:44:45          at PgBoss.start
09:44:45       (/home/xpub/node_modules/pg-boss/lib/index.js:116:36)
09:44:45          at startJobQueue
09:44:45       (/home/xpub/node_modules/pubsweet-server/src/jobs/index.js:60:16)
09:44:45          at startServer
09:44:45       (/home/xpub/node_modules/pubsweet-server/src/start-server.js:35:9)
```
Then, the setup of the tests is executed again and it is _the second time_ it is executed that finds the port in use:
```
09:44:45  Submission
09:44:45 test/helpers/setup.js::startServer
09:44:45 test/helpers/setup.js::startServer await start
09:45:32 events.js:183
09:45:32       throw er; // Unhandled 'error' event
09:45:32       ^
09:45:32 
09:45:32 Error: listen EADDRINUSE :::4000
09:45:32     at Server.setupListenHandle [as _listen2] (net.js:1360:14)
09:45:32     at listenInCluster (net.js:1401:12)
09:45:32     at Server.listen (net.js:1485:7)
09:45:32     at Server.tryCatcher (/home/xpub/node_modules/bluebird/js/release/util.js:16:23)
09:45:32     at ret (eval at makeNodePromisifiedEval (/home/xpub/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
09:45:32     at startServer (/home/xpub/node_modules/pubsweet-server/src/start-server.js:28:9)
09:45:32     at start (/home/xpub/node_modules/pubsweet/src/startup/start.js:14:31)
09:45:32     at <anonymous>
```
This confirms the "port in use" error as a side effect, and points to the original stack trace as a possible cause of the hung process. To be confirmed if we manage to have it hang again.

**Comment by giorgiosironi** [comment]
[build 5](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1230/5/pipeline/39/) reproduces the hung process.

**Comment by giorgiosironi** [comment]
Full output from hung process:
```
> NODE_CONFIG_ENV=test NODE_ENV=production testcafe "${BROWSER:-chrome}" 'test/**/*.browser.js' "--screenshots" "/tmp/screenshots" "--screenshots-on-fails"
clean-webpack-plugin: /home/xpub/_build/assets has been removed.

 Running tests in:
 - HeadlessChrome 71.0.3578 / Linux 0.0.0

 Submission
test/helpers/setup.js::startServer
test/helpers/setup.js::startServer await start
Type "TeamMemberMeta" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Object" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
test/helpers/setup.js::startServer
test/helpers/setup.js::startServer await start
test/helpers/setup.js::setup
test/helpers/setup.js::setup createTables
test/helpers/setup.js::setup
test/helpers/setup.js::setup createTables
test/helpers/setup.js::setup replaySetup
test/helpers/setup.js::setup await startS3Server
test/helpers/setup.js::teardown
test/helpers/setup.js::startServer
test/helpers/setup.js::setup
test/helpers/setup.js::setup createTables
error: select "manuscript".* from "manuscript" where "manuscript"."id" = $1 - relation "manuscript" does not exist message=select "manuscript".* from "manuscript" where "manuscript"."id" = $1 - relation "manuscript" does not exist, locations=[line=2, column=3], path=[savePage]
test/helpers/setup.js::setup replaySetup
test/helpers/setup.js::setup await startS3Server
test/helpers/setup.js::teardown
test/helpers/setup.js::setup
test/helpers/setup.js::setup createTables
test/helpers/setup.js::setup replaySetup
test/helpers/setup.js::setup await startS3Server
test/helpers/setup.js::teardown
test/helpers/setup.js::setup
test/helpers/setup.js::setup createTables
test/helpers/setup.js::setup replaySetup
test/helpers/setup.js::setup await startS3Server
error: Attempt to save Manuscript 9ccba7c7-404d-4a7f-8054-f8d0eb374f84 with updated=Fri Dec 21 2018 10:25:49 GMT+0000 (UTC)
test/helpers/setup.js::teardown
```

**Comment by giorgiosironi** [comment]
3 logs for `test/helpers/setup.js::startServer` which should only be executed once, are suspect. The 2 `test/helpers/setup.js::startServer await start` descend from that.

**Comment by giorgiosironi** [comment]
After patching the code I can run the tests individually, but not all together:
```
$ NODE_ENV=production NODE_CONFIG_ENV=test PGDATABASE=test_browser docker-compose -f docker-compose.yml -f docker-compose.ci.yml run -p 10081:10081 --rm app node_modules/.bin/testcafe "chrome:headless --no-sandbox" 'test/**/submission.browser.js' --dev 
TypeError: Cannot read property 'requestHooks' of null

    at Object.test (/home/xpub/test/lastStepVisited.browser.js:9:1)
```
Anyone spots the problem? Jenkins reproduces this.

**Comment by giorgiosironi** [comment]
I think `requestHooks` is a property of the `fixture` object, so TestCafé probably needs some declaration of that into the test file itself.

**Comment by giorgiosironi** [comment]
From what https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixtures says I guess you must specify `fixture(...)` in the test file, as it will globally interacts with the `test(...)` definition without any of the two having a reference to the other.

**Comment by giorgiosironi** [comment]
[build 10](https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-xpub/job/PR-1230/10/console) exhibits this:
```
13:36:49    1) - Error in fixture.before hook -
13:36:49       TimeoutError: Knex: Timeout acquiring a connection. The pool is
13:36:49       probably full. Are you missing a .transacting(trx) call?
13:36:49 
13:36:49       Browser: HeadlessChrome 71.0.3578 / Linux 0.0.0
13:36:49 
13:36:49          48 |    // A new query builder instance.
13:36:49          49 |    queryBuilder: function queryBuilder() {
13:36:49          50 |      return client.queryBuilder();
13:36:49          51 |    },
13:36:49          52 |    raw: function raw() {
13:36:49        > 53 |      return client.raw.apply(client, arguments);
13:36:49          54 |    },
13:36:49          55 |    batchInsert: function batchInsert(table, batch) {
13:36:49          56 |      var chunkSize = arguments.length > 2 && arguments[2]
13:36:49       !== undefined ? arguments[2] : 1000;
13:36:49          57 |
13:36:49          58 |      return (0, _batchInsert3.default)(this, table, batch,
13:36:49       chunkSize);
```
If the timeouts really are too short, this is another thing to configure. `knex` is accessed through `pgboss` which is accessed through `pubsweet` so not sure how to get there.

**Comment by giorgiosironi** [comment]
[build 12](https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-xpub/job/PR-1230/12/consoleFull) took more than 2 minutes to start the server:
```
13:43:41 test/helpers/setup.js::startServer await start
13:45:48 test/helpers/setup.js::startServer started
```
There may be other underlying failures in there, doing more runs.

**Comment by diversemix** [comment]
Just as a record of events...  Jenkins failed on the 23rd Dec ... @thewilkybarkid restart Jenkins this morning and we have since seen builds passing and failing.

**Comment by diversemix** [comment]
We are now working on the premise that if only one `elife-xpub` build runs at a time then they pass. Implying simultaneous builds seem to fail (which we have also seen).

**Comment by jyenes** [comment]
I think we are on the right hypothesis @diversemix as #1232 has passed running stand alone

**Comment by diversemix** [comment]
I suggest we keep this open for now - just to carry on recording our findings.... Next up #1231

**Comment by diversemix** [comment]
Further research shows that IPv6 is not configured in the docker containers....

```
root@5d499d073df6:~/config# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
71: eth0@if72: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.4/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
root@5d499d073df6:~/config# nslookup
bash: nslookup: command not found
root@5d499d073df6:~/config# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.4	5d499d073df6
```

This is relevant as the error reports the address in use is `:::4000`

**Pull request merged**
