### PR TITLE
Upgrade yarn to 1.10.1

### PR DESCRIPTION
**Pull request by damnhipster**
#### Background

We currently accept any version of yarn greater than 1.2.

1.10 introduced a new field in the `yarn.lock` file, which [gets stripped out when using earlier versions](https://github.com/yarnpkg/yarn/issues/6440)

We generally use the latest version of yarn locally, so this change will throw an error if an earlier version of yarn is used.

### CODE REVIEW

**Comment by diversemix** [comment]
Test failures looks like we have to update yarn in the docker image `xpub/xpub:base`

**Comment by diversemix** [comment]
```
$ docker pull xpub/xpub:base
base: Pulling from xpub/xpub
Digest: sha256:3b10abb05a9c8a3c69adb08fbc27ff5ab83bbb5a3d49014dee61a3e2bc519fd2
Status: Image is up to date for xpub/xpub:base
✔ ~/dev
$ docker run -it xpub/xpub:base bash
root@d327bb54037d:~# yarn --version
1.3.2
root@d327bb54037d:~# 
```

**Comment by damnhipster** [comment]
The [build and push job](https://gitlab.coko.foundation/yld/xpub-deployment-config-postgres/pipelines) doesn't seem to work, will build and push manually.

**Comment by damnhipster** [comment]
https://gitlab.coko.foundation/xpub/xpub is a separate project which also pushes it's images to the same location as our base image. We should look at changing this.

**Pull request merged**
