### PR TITLE
Allow remote debugging of test:browser

### PR DESCRIPTION
**Pull request by giorgiosironi**
To diagnose https://github.com/elifesciences/elife-xpub/issues/1228

### CODE REVIEW

**Comment by diversemix** [comment]
:drumroll:

**Comment by giorgiosironi** [comment]
The build is full of horrible output, that needs to be sorted. Port 10081 is temporarily open on all `containers` Jenkins nodes so given an ip address I can successfully connect through `chrome://inspect`. I don't see the pages yet, I was able to locally.

**Comment by giorgiosironi** [comment]
[build 5](https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-xpub/job/PR-1229/5) was killed by the 2-hour timeout, was hanging.
[build 6](https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-xpub/job/PR-1229/6/console) failed with `listen EADDRINUSE :::4000`. It ran on another node so it should be unrelated.

**Comment by giorgiosironi** [comment]
[build 7](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1229/7/pipeline) seems to be hung, investigating.

**Comment by giorgiosironi** [comment]
The browser responds well on the remote debugging interface, but seems to be pointed to an "idle" page rather than loading the application as I've seen locally.
screenshot from 2018-12-21 09-03-54
This leads me to think that the Chrome infrastructure works fine, but there is some problem in bootstrapping the application inside Testcafe.

**Comment by giorgiosironi** [comment]
Given it continues to hangs here, should wait for https://github.com/elifesciences/elife-xpub/pull/1230 to get some logs about it.

**Comment by damnhipster** [comment]
Image seems to build correctly: https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1229/9/pipeline/22

**Comment by giorgiosironi** [comment]
Green for some runs now, but I'm going to strip the enabling from this PR to get it merged (leaving just the debugger part).

**Pull request merged**
