### PR TITLE
fix(elife-theme): use elifesciences org instead of pubsweet for theme

### PR DESCRIPTION
**Pull request by dryhten**
re #215

### CODE REVIEW

**Comment by dryhten** [comment]
Note that `yarn.lock` didn't want to get updated and `CHANGELOG.md` for the theme should be updated as well.

**Comment by jsms90** [comment]
Can't merge without a 2nd person :sweat:

**Comment by dryhten** [comment]
@jsms90 hannah merged it by force (I don't know what method she used). I assume I can manually merge this commit too from the terminal, but I don't know if it's that urgent to have it. We should test locally before we publish new versions of the theme package anyway.

**Comment by hdrury1** [comment]
Just wanted to point out that @elifesciences/elife-theme is the eLife 2.0 theme, rather than the eLife xPub theme and the two don't match in terms of variables. Is that an issue?

**Comment by jsms90** [comment]
As discussed at standup, the readme is just out of date on https://www.npmjs.com/package/@elifesciences/elife-theme, whereas the code itself reflects the correct variables and values :+1:

This is really common, whenever a readme documents exactly what code that is written. The code gets updated, but the docs do not. Otherwise, every time you make an update to the code, you need to make an identical update in the documentation, which is just a bit of a waste. In the case of a theme, the code is self-documenting.

So, to avoid this kind of confusion in future, we're probably better off removing the code itself from the readme - see [my review for the other PR](https://github.com/elifesciences/elife-xpub/pull/233#pullrequestreview-130303406) :smile: 

Seems like this is ready to merge @hdrury1? And we can make the necessary updates in the other PR?

**Comment by dryhten** [comment]
@hdrury1 as discussed at the standup, I'm not entirely sure what eLife xPub theme is, I've never seen or used it before, and couldn't find it in any repository. The only theme we ever used it the elife-theme that I pushed to this repository.

The [README.md](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/README.md) file from the elife-theme seems to copy the SASS variables from here https://github.com/elifesciences/pattern-library/blob/develop/assets/sass/_variables.scss

We are using javascript variables now and not SASS ones. So the readme should be changed or removed as Jen mentioned.

@jsms90 just to make sure everything is clear, that node package you linked to is the same with this directory in this repository https://github.com/elifesciences/elife-xpub/tree/develop/client/elife-theme

**Pull request merged**
