### PR TITLE
Using tablet breakpoint on dashboard

### LINKED ISSUE #1000: Dashboard list items incorrectly sized between smallest and mid breakpoint
🎖 1000th ticket! 🎖 

**Describe the bug**
Between 480px and 768px the dashboard list item component is displaying incorrectly. The vertical spacing between the status and last updated date is too large.

**To Reproduce**
1. Go to 'https://staging--xpub.elifesciences.org/'
2. Resize window to betwen 480px and 768px
3. Observe incorrectly sized dashboard list item

**Expected behavior**
The dashboard list item should behave in the same way between 480px and 768px as below 468px.

**Screenshots**

screen shot 2018-11-07 at 14 18 38

Designs:

screen shot 2018-11-07 at 14 28 01

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Firefox

### PR DESCRIPTION
**Pull request by damnhipster**
#### Background

Uses tablet portrait breakpoint for dashboard list items, to apply either mobile or desktop designs.

You can see the breakpoints [here](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/index.js#L61) and [here](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/global/layout/media.js#L4-L9)

#### Any relevant tickets

Closes #1000 

#### How has this been tested?

Review environment

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Just an heads up that I am re-triggering the Jenkins job to explore how the new review environments will work there, some of the checks will be oscillating between green/yellow.

**Comment by giorgiosironi** [comment]
Unstable, see https://github.com/elifesciences/elife-xpub/pull/1053 for a fix-in-progress. You can ignore the Jenkins check for now.

**Comment by damnhipster** [comment]
@hdrury1 @chugginselifesciences What do you think?

**Comment by hdrury1** [comment]
@damnhipster The date text looks a little on the small side... according to designs it should match the 'Today' text:

screen shot 2018-11-16 at 10 46 55

**Comment by damnhipster** [comment]
@hdrury1 Updated:

screen shot 2018-11-16 at 10 56 51

**Pull request merged**
