### PR TITLE
1585 - redirect content

### LINKED ISSUE #1585: Add content to https://reviewer.elifesciences.org/redirect
## Problem / Motivation
- WHO wants this? Authors and product
- WHEN and WHERE do they want it? This page will form part of the journey for users who attempt to begin a new submission in eJP and need to be redirected after we are supporting 100% of new submissions through xPub.
- WHAT do they want? Information explaining that they are being redirected and why
- WHY do they want this? We were unable to implement the redirection on submit.elifesciences.org as originally planned, so there may still be some users attempting to begin new initial submissions in eJP. This interstitial will provide enough context to support this less than desirable user journey. 

## Proposed solution
This follows work undertaken as part of #1584 

- For a first implementation, the page will not be responsive but will reflect the content as designed for screen widths 1000px and below (i.e. without the image)

See https://projects.invisionapp.com/share/RHQP0Q42D39#/screens/348816745

- The page will not contain the global navigation bar
- The logo is for display purposes only and is not clickable
- 'Terms and conditions' is an external link to https://elifesciences.org/terms
- 'Privacy policy' is an external link to https://elifesciences.org/privacy
- Continue button directs to https://reviewer.elifesciences.org where the user journey continues as currently

## Clarification needed and assumptions
- Responsiveness will be introduced as a secondary task
- The image will be added as a secondary task

---

## Tasks

- [ ] A description of a task
- [ ] A description

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes
screen shot 2019-02-26 at 14 06 25

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

This PR should add content to the `/redirect` page. This page should contain a button to the dashboard page and some links in the footer to the T&C page and Privacy statement.

#### Any relevant tickets

closes #1585 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [x] Unit / Integration tests
- [x] Browser tests
- [ ] End2end tests

#### UI Changes

- [x] Has been reviewed against Designs
- [x] Necessary updates to styleguide

### CODE REVIEW

**Comment by Cooryd** [comment]
@hdrury1 / @chugginselifesciences Could this be design reviewed and approved before it gets merged in please.

**Review by hem-brahmbhatt — APPROVED** [review]

**Comment by hdrury1** [comment]
@Cooryd Chris is off this week but with my non-designer's eye it looks like the button should be wider, the text should cover 6 columns and the 'Terms and conditions' text should be aligned to the left (up to 1272px)

**Design**

screen shot 2019-03-04 at 11 35 53

**Implementation**

screen shot 2019-03-04 at 11 36 31

**Review by SemraSh — COMMENTED** [review]
May be we can add browser test for the `/redirect` page, and test if the links (terms | conditions) are returning 200 so if they change in the future the test will fail.

**Comment by Cooryd** [comment]
@hdrury1 I'm fine to add this (have added a `large` prop that gives it override styling), but it's inconsistent with all other use of this button so far in the app. Also we are still using the `fontHeading` font for `Button`'s which isn't what's used in this design. Heres what it looks like now:

screenshot 2019-03-04 at 12 30 45

Here's it with the normal font type:

screenshot 2019-03-04 at 12 31 35


I can apply this to the `large` buttons or to all buttons or leave as is (I think think it looks better without the semi-bold font styling it currently has)

---
@SemraSh 

Good idea to add a browser test, however I'll add it to check the 'continue' button instead. Checking for 200 responses from the other links would be a e2e test scenario as they're external links

**Review by hdrury1 — APPROVED** [review]
lgtm

**Review by SemraSh — APPROVED** [review]

**Pull request merged**
