### PR TITLE
Test review environments

### PR DESCRIPTION
**Pull request by giorgiosironi**
#### Background

Currently open pull requests do not get to the review environment stage, so creating one without changes to test the full process.

#### Any relevant tickets

Reproduces https://github.com/elifesciences/elife-xpub/issues/2036

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Fails browser tests on the first attempt.

**Comment by giorgiosironi** [comment]
They also failed in the [last 4 `develop` builds](https://alfred.elifesciences.org/job/test-elife-xpub-source-repository/) so not encouraging.

**Comment by giorgiosironi** [comment]
Got logs out of this build, they are what we expected:
```
$ kubectl logs elife-xpub--pr-2038-86c9b98947-qgdz6 elife-xpub-setupdb
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
info: Starting Application: elife-xpub--pr-2038-86c9b98947-qgdz6, PID: 15
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
info: Checking if database tables exist.
info: Database tables exist.
info: Received the following answers:
info:   username: pubsweet
info:   email: fake@example.com
info:   password: <redacted>
info:   clobber: true
info: Setting up the database
info: Overwriting existing database due to clobber option
info: Creating user pubsweet
error: Database setup failed
error: ValidationError: username is not a property in User's schema
    at validationError (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:11:3)
    at Object.keys.forEach.prop (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:180:15)
    at Array.forEach (<anonymous>)
    at User.updateProperties (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:176:29)
    at new BaseModel (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:29:12)
    at new User (/home/xpub/packages/component-model-user/entities/user/index.js:5:1)
    at module.exports (/home/xpub/node_modules/pubsweet/node_modules/@pubsweet/db-manager/src/commands/add-user.js:10:16)
    at module.exports (/home/xpub/node_modules/pubsweet/node_modules/@pubsweet/db-manager/src/commands/setup-db.js:17:11)
    at <anonymous>
info: Stopping Application: elife-xpub--pr-2038-86c9b98947-qgdz6, PID: 15
```

**Comment by erezmus** [comment]
The issue comes from the @pubsweet/db-manager in src/setup-db.js, after creating the tables, it creates a new user with the User model (see src/add-user.js) with the the 'username', 'password', 'admin' and 'email' fields.

However our User model (and table) don't have any of those fields.

**Comment by erezmus** [comment]
closed via PR #2054

**Pull request closed without merging**
