### PR TITLE
Port Styleguide on Jenkins

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/elifesciences/elife-xpub/issues/939

Jenkins nodes have their own credentials and `aws` cli preinstalled, so they can easily deal with this use case.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The commit status leads to https://s3.amazonaws.com/ci-elife-xpub-styleguide/1168/index.html now, can someone check it works as expected?

**Comment by damnhipster** [comment]
Can we run this for the main branch as well? i.e. `develop`

**Comment by giorgiosironi** [comment]
> Can we run this for the main branch

Yes, I didn't want to clash with the Gitlab version so I'll do that with a follow-up PR.

**Comment by giorgiosironi** [comment]
> Do we have a similar (or the same) task to tear these down as we do for review environments?

We could, but usually (e.g. `pattern-library`) don't bother as there is no resource limit on S3 and the cost of keeping them there is very low.

**Pull request merged**
